# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 575efa161eaa1f0fbb2113b4c85334a0f6b2ccd406f51a5b6318c70ce1e7d5f129a44eec7225b1af9e3263419d334588fdb2534cc25e6666a910eae673344d5b

test:
  secret_key_base: 5ce512c661941a8dce127e78a35e2222acd04c0b4646dff027e0a1bf8fdd6798810396fb39875318bb89745d751ce1d8e09ad18d14d384621af575ef944a87fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
